services:

  postgres:
    image: postgres:16
    container_name: monitoramento-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: monitoramento-backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: monitoramento-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

  broker:
    image: eclipse-mosquitto:2
    container_name: railsense-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log: