services:

    postgres:
        image: postgres:16
        container_name: monitoramneto-db
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        Volumes:
            - postgres_data:/var/lib/postgresql/data
    
    backend:
        build:
            context: ./backend
        container_name: monitoramento-backend
        restart: always
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
            GEMINI_API_KEY: ${GEMINI_API_KEY}
            CLAUDINARY_URL: ${CLAUDINARY_URL}
        ports:
            - "8080:8080"
    
    frontend:
        build:
            context: ./frontend
        container_name: monitoramento-frontend
        restart: always
        depends_on:
            - backend
        ports: "3000:80"

volumes:
    postgres_data